apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo-prod
resources:
- ../../base
- namespace.yaml
patches:
- path: release.yaml
images:
- name: course/productpage
  newName: 111122223333.dkr.ecr.us-east-1.amazonaws.com/devops-course-prod/productpage
  newTag: REPLACE_WITH_COMMIT_SHA
- name: course/details
  newName: 111122223333.dkr.ecr.us-east-1.amazonaws.com/devops-course-prod/details
  newTag: REPLACE_WITH_COMMIT_SHA
- name: course/ratings
  newName: 111122223333.dkr.ecr.us-east-1.amazonaws.com/devops-course-prod/ratings
  newTag: REPLACE_WITH_COMMIT_SHA
- name: course/reviews
  newName: 111122223333.dkr.ecr.us-east-1.amazonaws.com/devops-course-prod/reviews
  newTag: REPLACE_WITH_COMMIT_SHA
