apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-prod
  namespace: argocd
spec:
  project: bookinfo
  source:
    repoURL: https://github.com/REPLACE_OWNER/REPLACE_REPO.git
    targetRevision: main
    path: gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
